# 构建阶段
FROM node:20-alpine AS builder

WORKDIR /app

RUN npm install -g pnpm@10.25.0

COPY pnpm-workspace.yaml pnpm-lock.yaml package.json turbo.json ./
COPY packages ./packages
COPY apps/web ./apps/web

RUN pnpm install --frozen-lockfile
RUN pnpm --filter=@xingliu/config build
RUN pnpm --filter=@xingliu/web build


# 运行阶段
FROM node:20-alpine

WORKDIR /app

RUN npm install -g pnpm@10.25.0
RUN apk add --no-cache dumb-init

COPY pnpm-workspace.yaml pnpm-lock.yaml package.json ./
COPY packages ./packages
COPY apps/web ./apps/web

RUN pnpm install --frozen-lockfile --prod --ignore-scripts

COPY --from=builder /app/apps/web/.next ./apps/web/.next
COPY --from=builder /app/packages/config/dist ./packages/config/dist
COPY --from=builder /app/apps/web/public ./apps/web/public

ENV NODE_ENV=production
ENV PORT=8080

EXPOSE 8080

ENTRYPOINT ["dumb-init", "--"]

CMD ["pnpm", "--filter=@xingliu/web", "start"]
